// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyQuanBilliard.Models;

#nullable disable

namespace QuanLyQuanBilliard.Migrations
{
    [DbContext(typeof(QuanLyQuanBilliardContext))]
    [Migration("20240930035341_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuanLyQuanBilliard.Models.EF.Ban", b =>
                {
                    b.Property<int>("BanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BanId"), 1L, 1);

                    b.Property<long>("GiaGio")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayCapNhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BanId");

                    b.ToTable("Bans");
                });

            modelBuilder.Entity("QuanLyQuanBilliard.Models.EF.HoaDon", b =>
                {
                    b.Property<int>("HoaDonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoaDonId"), 1L, 1);

                    b.Property<int>("BanId")
                        .HasColumnType("int");

                    b.Property<long>("GiaGio")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<int?>("TheThanhVienId")
                        .HasColumnType("int");

                    b.Property<long>("TongTien")
                        .HasColumnType("bigint");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HoaDonId");

                    b.HasIndex("BanId");

                    b.HasIndex("NhanVienId");

                    b.HasIndex("TheThanhVienId");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("QuanLyQuanBilliard.Models.EF.HoaDonChiTiet", b =>
                {
                    b.Property<int>("HoaDonChiTietId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoaDonChiTietId"), 1L, 1);

                    b.Property<long>("GiaBan")
                        .HasColumnType("bigint");

                    b.Property<long>("GiaNhap")
                        .HasColumnType("bigint");

                    b.Property<int>("HoaDonId")
                        .HasColumnType("int");

                    b.Property<int>("IdKho")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("HoaDonChiTietId");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("IdKho");

                    b.ToTable("HoaDonChiTiets");
                });

            modelBuilder.Entity("QuanLyQuanBilliard.Models.EF.Kho", b =>
                {
                    b.Property<int>("IdMatHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMatHang"), 1L, 1);

                    b.Property<long>("GiaBan")
                        .HasColumnType("bigint");

                    b.Property<long>("GiaNhap")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayCapNhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenMatHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdMatHang");

                    b.ToTable("Khos");
                });

            modelBuilder.Entity("QuanLyQuanBilliard.Models.EF.Luong", b =>
                {
                    b.Property<int>("LuongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LuongId"), 1L, 1);

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<long>("LuongCoBan")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("NgayCapNhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Thang")
                        .HasColumnType("datetime2");

                    b.Property<long>("Thuong")
                        .HasColumnType("bigint");

                    b.HasKey("LuongId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("Luongs");
                });

            modelBuilder.Entity("QuanLyQuanBilliard.Models.EF.NhanVien", b =>
                {
                    b.Property<int>("NhanVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhanVienId"), 1L, 1);

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<long>("LuongCoBan")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("NgayBatDauLam")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayCapNhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("NhanVienId");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("QuanLyQuanBilliard.Models.EF.TaiKhoan", b =>
                {
                    b.Property<int>("TaiKhoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaiKhoanId"), 1L, 1);

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayCapNhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TaiKhoanId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("QuanLyQuanBilliard.Models.EF.TheThanhVien", b =>
                {
                    b.Property<int>("TheThanhVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TheThanhVienId"), 1L, 1);

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayCapNhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TheThanhVienId");

                    b.ToTable("TheThanhViens");
                });

            modelBuilder.Entity("QuanLyQuanBilliard.Models.EF.HoaDon", b =>
                {
                    b.HasOne("QuanLyQuanBilliard.Models.EF.Ban", "Ban")
                        .WithMany()
                        .HasForeignKey("BanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyQuanBilliard.Models.EF.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyQuanBilliard.Models.EF.TheThanhVien", "TheThanhVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("TheThanhVienId");

                    b.Navigation("Ban");

                    b.Navigation("NhanVien");

                    b.Navigation("TheThanhVien");
                });

            modelBuilder.Entity("QuanLyQuanBilliard.Models.EF.HoaDonChiTiet", b =>
                {
                    b.HasOne("QuanLyQuanBilliard.Models.EF.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyQuanBilliard.Models.EF.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("IdKho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("Kho");
                });

            modelBuilder.Entity("QuanLyQuanBilliard.Models.EF.Luong", b =>
                {
                    b.HasOne("QuanLyQuanBilliard.Models.EF.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyQuanBilliard.Models.EF.TaiKhoan", b =>
                {
                    b.HasOne("QuanLyQuanBilliard.Models.EF.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyQuanBilliard.Models.EF.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("QuanLyQuanBilliard.Models.EF.TheThanhVien", b =>
                {
                    b.Navigation("HoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
